export const FETCH_USER = "FETCH_USER";

export const FETCH_SURVEYS = "FETCH_SURVEYS";

export const SUBMIT_SURVEY = "SUBMIT_SURVEY";
export const SUBMIT_SURVEY_SUCESS = "SUBMIT_SURVEY_SUCESS";
export const SUBMIT_SURVEY_FAIL = "SUBMIT_SURVEY_FAIL";
